Implemented helper service #closes 4
akai-org/discord-bot-py pull request #20
Opened 2022-04-19 12:21 UTC by JanekDev

2022-04-19 12:24 UTC, JanekDev commented
Propozycja - można zamiast standardowej wiadomości tekstowej mieć jedną, aktualizowaną co jakiś czas na kanale z wiadomością powitalną - (kanał info?). Propozycja takiej wiadomości:
![Screenshot_1](https://user-images.githubusercontent.com/52979291/164002863-6ededc65-09c8-4ec0-b772-9c56475c24a2.png)

2022-04-19 19:06 UTC, radswn commented
Zrebase'ujcie sb zmiany, bo dzisiaj merge'owałem mojego PRa i jest trochę konfliktów

2022-04-19 19:20 UTC, radswn requested changes

2022-04-19 19:20 UTC, radswn commented on akaibot.py
> +        #helper service handler
komentarz raczej zbędny

2022-04-19 19:20 UTC, radswn commented on database/repositories/helper.py
>          self.helper_model = helper_range_model
jak już rozdzielacie na helper_range_model i helper_reward_model, to ta zmienna też mogłaby się nazywać helper_range_model tak jak niżej

2022-04-19 19:20 UTC, radswn commented on services/command.py
> +            #TODO add beautiful print
takie komenty to też nie ma co zostawiać imo, na upiększanie printów jeszcze przyjdzie czas :D

2022-04-19 19:20 UTC, radswn commented on services/helper.py
> +                self.logger.debug(f'User {thanked.display_name} got {p} point from '
taki bajer: `... got {p} point{"" if p == 1 else "s"} from ...` polecam zamiast tego ifa dużego, niżej to samo
właśnie takie _pythonic way_ bajery miałem na myśli jak zwróciłem na to uwagę w poprzednim PRze :D wiele można w tym pythonie robić co się filozofom nie śniło

2022-04-19 19:28 UTC, radswn commented
> 

no nie wiem, przegadamy to na spotkaniu, ale jak dla mnie to aktualna forma jest wystarczająca :)

2022-04-20 06:10 UTC, radswn requested changes

2022-04-20 06:10 UTC, radswn commented on services/helper.py
> +            self.repository.add_points_to_user(thanked.id, -p)
nie zauważyłem tego wcześniej, ale nie możnaby tych dwóch funkcji `add_points` i `remove_points` spiąć w jednej `calculate_points` na przykład?
myślałem że różnią się one składnią, ale tu i tam podajesz p lub -p do funkcji `add_points_to_user`

Na pewno można chociaż część tych funkcji wydzielić do innego miejsca, aby uniknąć powtórzeń

2022-04-20 06:10 UTC, radswn commented on database/repositories/helper.py
> +        return emojis
daj tego newline'a od razu, bo prędzej czy później i tak jakiś reformat automatyczny go doda, a tym sposobem nie zakradnie się to do innego PRa z dupy

2022-04-20 06:10 UTC, radswn commented on database/repositories/helper.py
> +        self.helper_reward_model = helper_reward_model
w sumie można się pozbyć przedrostka `helper_` w tych dwóch polach, bo i tak wiadomo że to od helpera

2022-04-20 16:17 UTC, radswn approved these changes

2022-04-20 16:17 UTC, merged