Sprzątanie bazy, wczytywanie z YAML'a - closes #19
akai-org/discord-bot-py pull request #34
Opened 2022-05-11 21:09 UTC by JanekDev

2022-05-11 22:21 UTC, JanekDev commented
Po zrobieniu rebase z maina jest problem z inicjalizacją usługi ranking - można łatwo naprawić przez usunięcie command_repository w linii 92, dajcie znać czy w tym PR to zrobić czy osobnym.

2022-05-12 12:35 UTC, radswn requested changes

2022-05-12 12:35 UTC, radswn commented on database/repositories/settings.py
> +        session.close()
dużo duplikatów z tą funkcją `load_from_yaml` w osobnych repo, wydziel to do jednej

2022-05-12 12:35 UTC, radswn commented on db.yaml.example
> +  # test: "response on test"
te trzy linijki można zredukować do jednej przykładowej dla każdej tabeli

2022-05-12 12:35 UTC, radswn commented on db.yaml.example
> +  # neccesary entries (just uncomment them)
ale te wartości stałe mogą być tak jak są

2022-05-13 05:13 UTC, radswn commented
> Po zrobieniu rebase z maina jest problem z inicjalizacją usługi ranking - można łatwo naprawić przez usunięcie command_repository w linii 92, dajcie znać czy w tym PR to zrobić czy osobnym.

Zrób w tym, też na to zwróciłem uwagę

2022-05-19 10:11 UTC, radswn approved these changes

2022-05-19 10:11 UTC, merged